const data = {
  stocks: [
    {
      _id: '1',
      title: "FTEG",
      twitter: "https://mobile.twitter.com/search?q=%24FTEG&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/FTEG?p=FTEG&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/for-the-earth-pk-FTEG/trades",
      fillings:"https://www.otcmarkets.com/stock/FTEG/disclosure",  
      news:"https://www.globenewswire.com/search/organization/For%252520The%252520Earth%252520Corp%C2%A7",
      price: "https://api.twelvedata.com/time_series?symbol=FTEG&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=FTEG&apikey=a5e118f7893f4e8f9428f4ef74206850",    
    },
    {
      _id: '2',
      title: "BDGR",
      twitter: "https://mobile.twitter.com/search?q=%24BDGR&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/BDGR?p=BDGR&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/black-dragon-resource-co-pk-BDGR/trades",
      fillings:"https://www.otcmarkets.com/stock/BDGR/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Black%252520Dragon%252520Resource%252520Companies%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=BDGR&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=BDGR&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
    {
      _id: '3',
      title: "AITX",
      twitter: "https://mobile.twitter.com/search?q=%24AITX&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/AITX?p=AITX&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/artificial-intelligence-pk-AITX/trades",
      fillings:"https://www.otcmarkets.com/stock/AITX/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Artificial%252520Intelligence%252520Technology%252520Solutions", 
      price: "https://api.twelvedata.com/time_series?symbol=AITX&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=AITX&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
    {
      _id: '4',
      title: "MLHC",
      twitter: "https://mobile.twitter.com/search?q=%24MLHC&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/MLHC?p=MLHC&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/m-line-pk-MLHC/trades",
      fillings:"https://www.otcmarkets.com/stock/MLHC/disclosure",  
      news:"https://www.globenewswire.com/search/organization/M%252520Line%252520Holdings%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=MLHC&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=MLHC&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
    {
      _id: '5',
      title: "UBQU",
      twitter: "https://mobile.twitter.com/search?q=%24UBQU&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/UBQU?p=UBQU&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/ubiquitech-software-pk-UBQU/trades",
      fillings:"https://www.otcmarkets.com/stock/UBQU/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Ubiquitech%252520Software%252520LLC",  
      price: "https://api.twelvedata.com/time_series?symbol=UBQU&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=UBQU&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
    {
      _id: '6',
      title: "GARB",
      twitter: "https://mobile.twitter.com/search?q=%24GARB&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GARB?p=GARB&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/garb-oil-and-power-pk-GARB/trades",
      fillings:"https://www.otcmarkets.com/stock/GARB/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Garb%252520Oil%252520&%252520Power%252520Corporation", 
      price: "https://api.twelvedata.com/time_series?symbol=GARB&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=GARB&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
    {
      _id: '7',
      title: "ONCI",
      twitter: "https://mobile.twitter.com/search?q=%24ONCI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ONCI?p=ONCI&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/on4-communications-pk-ONCI/trades",
      fillings:"https://www.otcmarkets.com/stock/ONCI/disclosure",  
      news:"https://www.globenewswire.com/search/organization/ON4%252520Communications%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=ONCI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=ONCI&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
    {
      _id: '8',
      title: "HAON",
      twitter: "https://mobile.twitter.com/search?q=%24HAON&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/HAON?p=HAON&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/halitron-pk-HAON/trades",
      fillings:"https://www.otcmarkets.com/stock/HAON/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Halitron%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=HAON&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=HAON&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
    {
      _id: '9',
      title: "IPSI",
      twitter: "https://mobile.twitter.com/search?q=%24IPSI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/IPSI?p=IPSI&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/innovative-payment-solut-qb-IPSI/trades",
      fillings:"https://www.otcmarkets.com/stock/IPSI/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Innovative%252520Payment%252520Solutions%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=IPSI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=IPSI&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
    {
      _id: '10',
      title: "CUBT",
      twitter: "https://mobile.twitter.com/search?q=%24CUBT&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/CUBT?p=CUBT&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/curative-biotechnology-pk-CUBT/trades",
      fillings:"https://www.otcmarkets.com/stock/CUBT/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Connectyx%252520Technologies%252520Holdings%252520Group%CE%B4%252520Inc",  
      price: "https://api.twelvedata.com/time_series?symbol=CUBT&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=CUBT&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
    {
      _id: '11',
      title: "HPNN",
      twitter: "https://mobile.twitter.com/search?q=%24HPNN&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/HPNN?p=HPNN&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/hop-on-pk-HPNN/trades",
      fillings:"https://www.otcmarkets.com/stock/HPNN/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Hop-on%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=HPNN&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=HPNN&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
    {
      _id: '12',
      title: "RSHN",
      twitter: "https://mobile.twitter.com/search?q=%24RSHN&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/RSHN?p=RSHN&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/rushnet-pk-RSHN/trades",
      fillings:"https://www.otcmarkets.com/stock/RSHN/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/RushNet%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=RSHN&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=RSHN&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
    {
      _id: '13',
      title: "GDET",
      twitter: "https://mobile.twitter.com/search?q=%24GDET&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GDET?p=GDET&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/gd-entertainment-and-tec-pk-GDET/trades",
      fillings:"https://www.otcmarkets.com/stock/GDET/disclosure",  
      news:"https://www.globenewswire.com/search/organization/GD%252520Entertainment%252520&%252520Technology%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=GDET&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=GDET&apikey=a5e118f7893f4e8f9428f4ef74206850", 
    },
    {
      _id: '14',
      title: "GRLF",
      twitter: "https://mobile.twitter.com/search?q=%24GRLF&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GRLF?p=GRLF&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/green-leaf-innovations-pk-GRLF/trades",
      fillings:"https://www.otcmarkets.com/stock/GRLF/disclosure",  
      news:"https://www.globenewswire.com",  
      price: "https://api.twelvedata.com/time_series?symbol=GRLF&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=GRLF&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
    {
      _id: '15',
      title: "IGEX",
      twitter: "https://mobile.twitter.com/search?q=%24IGEX&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/IGEX?p=IGEX&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/indo-global-exchanges-pte-pk-IGEX/trades",
      fillings:"https://www.otcmarkets.com/stock/IGEX/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Indo%252520Global%252520Exchange%252520Pte%C2%A7%CE%B4%252520LTD",
      price: "https://api.twelvedata.com/time_series?symbol=IGEX&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=IGEX&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
      {
      _id: '16',
      title: "EFIR",
      twitter: "https://mobile.twitter.com/search?q=%24EFIR&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/EFIR?p=EFIR&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/egpi-firecreek-pk-EFIR/trades",
      fillings:"https://www.otcmarkets.com/stock/EFIR/disclosure",  
      news:"https://www.globenewswire.com/search/organization/EGPI%252520Firecreek%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=EFIR&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=EFIR&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
      {
      _id: '17',
      title: "BRZL",
      twitter: "https://mobile.twitter.com/search?q=%24BRZL&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/BRZL?p=BRZL&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/scepter-pk-BRZL/trades",
      fillings:"https://www.otcmarkets.com/stock/BRZL/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/BRZL",  
      price: "https://api.twelvedata.com/time_series?symbol=BRZL&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=BRZL&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '18',
      title: "MEDV",
      twitter: "https://mobile.twitter.com/search?q=%24MEDV&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/COPRF?p=COPRF&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/medivolve-pk-COPRF/trades",
      fillings:"https://www.otcmarkets.com/stock/COPRF/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/Medivolve%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=COPRF&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=COPRF&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '19',
      title: "VGID",
      twitter: "https://mobile.twitter.com/search?q=%24VGID&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/VGID?p=VGID&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/v-pk-VGID/trades",
      fillings:"https://www.otcmarkets.com/stock/VGID/disclosure",  
      news:"https://www.globenewswire.com/search/organization/V%252520Group%CE%B4%252520Inc",  
      price: "https://api.twelvedata.com/time_series?symbol=VGID&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=VGID&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
   {
      _id: '20',
      title: "SRMX",
      twitter: "https://mobile.twitter.com/search?q=%24SRMX&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/SRMX?p=SRMX&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/saddle-ranch-media-pk-SRMX/trades",
      fillings:"https://www.otcmarkets.com/stock/SRMX/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/Saddle%252520Ranch%252520Media%252520Inc",  
      price: "https://api.twelvedata.com/time_series?symbol=SRMX&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=SRMX&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '21',
      title: "PRPM",
      twitter: "https://mobile.twitter.com/search?q=%24PRPM&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/PRPM?p=PRPM&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/protek-capital-pk-PRPM/trades",
      fillings:"https://www.otcmarkets.com/stock/PRPM/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/protek%252520CAPITAL",  
      price: "https://api.twelvedata.com/time_series?symbol=PRPM&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=PRPM&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
   {
      _id: '22',
      title: "HCMC",
      twitter: "https://mobile.twitter.com/search?q=%24HCMC&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/HCMC?p=HCMC&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/healthier-choices-manage-pk-HCMC/trades",
      fillings:"https://www.otcmarkets.com/stock/HCMC/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/Healthier%252520Choices%252520Management%252520Corp",  
      price: "https://api.twelvedata.com/time_series?symbol=HCMC&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=HCMC&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '23',
      title: "QBAN",
      twitter: "https://mobile.twitter.com/search?q=%24QBAN&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/QBAN?p=QBAN&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/telco-cuba-pk-QBAN/trades",
      fillings:"https://www.otcmarkets.com/stock/QBAN/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/Telco%252520CUBA%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=QBAN&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=QBAN&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
   {
      _id: '24',
      title: "MMEX",
      twitter: "https://mobile.twitter.com/search?q=%24MMEX&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/MMEX?p=MMEX&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/mmex-resources-pk-MMEX/trades",
      fillings:"https://www.otcmarkets.com/stock/MMEX/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/MMEX%252520Resources%252520Corp%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=MMEX&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=MMEX&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '25',
      title: "MNGG",
      twitter: "https://mobile.twitter.com/search?q=%24MNGG&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/MNGG?p=MNGG&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/mining-global-pk-MNGG/trades",
      fillings:"https://www.otcmarkets.com/stock/MNGG/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Mining%252520Global%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=MNGG&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=MNGG&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
{
      _id: '26',
      title: "ICNM",
      twitter: "https://mobile.twitter.com/search?q=%24iCNM&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ICNM?p=ICNM&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/icon-media-pk-ICNM/trades",
      fillings:"https://www.otcmarkets.com/stock/ICNM/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Icon%252520Media%252520Holdings%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=ICNM&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=ICNM&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '27',
      title: "IDGC",
      twitter: "https://mobile.twitter.com/search?q=%24IDGC&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/IDGC?p=IDGC&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/id-global-pk-IDGC/trades",
      fillings:"https://www.otcmarkets.com/stock/IDGC/disclosure",  
      news:"https://www.globenewswire.com/search/organization/ID%252520Global%252520Corporation",  
      price: "https://api.twelvedata.com/time_series?symbol=IDGC&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=IDGC&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
   {
      _id: '28',
      title: "AZFL",
      twitter: "https://mobile.twitter.com/search?q=%24AZFL&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/AZFL?p=AZFL&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/amazonas-florestal-pk-AZFL/trades",
      fillings:"https://www.otcmarkets.com/stock/AZFL/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Amazonas%252520Florestal%252520Ltd%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=AZFL&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=AZFL&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '29',
      title: "CZNI",
      twitter: "https://mobile.twitter.com/search?q=%24CZNI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/CZNI?p=CZNI&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/cruzani-pk-CZNI/trades",
      fillings:"https://www.otcmarkets.com/stock/CZNI/disclosure",  
      news:"https://www.globenewswire.com/search/organization/CRUZANI%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=CZNI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=CZNI&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '30',
      title: "USMJ",
      twitter: "https://mobile.twitter.com/search?q=%24USMJ&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/USMJ?p=USMJ&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/north-american-cannabis-pk-USMJ/trades",
      fillings:"https://www.otcmarkets.com/stock/USMJ/disclosure",  
      news:"https://www.globenewswire.com/search/organization/North%252520American%252520Cannabis%252520Holdings%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=USMJ&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=USMJ&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '31',
      title: "NUUU",
      twitter: "https://mobile.twitter.com/search?q=%24NUUU&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/NUUU?p=NUUU&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/rejuvel-bio-sciences-pk-NUUU/trades",
      fillings:"https://www.otcmarkets.com/stock/NUUU/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/NUUU",  
      price: "https://api.twelvedata.com/time_series?symbol=NUUU&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=NUUU&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '32',
      title: "VIZC",
      twitter: "https://mobile.twitter.com/search?q=%24VIZC&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/VIZC?p=VIZC&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/vizconnect-pk-VIZC/trades",
      fillings:"https://www.otcmarkets.com/stock/VIZC/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/VIZC",  
      price: "https://api.twelvedata.com/time_series?symbol=VIZC&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=VIZC&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '33',
      title: "PLPL",
      twitter: "https://mobile.twitter.com/search?q=%24PLPL&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/PLPL?p=PLPL&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/plandai-biotechnology-pk-PLPL/trades",
      fillings:"https://www.otcmarkets.com/stock/PLPL/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/Plandai%252520Biotechnology%CE%B4%252520Inc%C2%A7",
      price: "https://api.twelvedata.com/time_series?symbol=PLPL&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=PLPL&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '34',
      title: "NOUV",
      twitter: "https://mobile.twitter.com/search?q=%24NOUV&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/NOUV?p=NOUV&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/nouveau-life-pharmaceuti-pk-NOUV/trades",
      fillings:"https://www.otcmarkets.com/stock/NOUV/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/Nouveau%252520Life%252520Pharmaceuticals%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=NOUV&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=NOUV&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '35',
      title: "MTVX",
      twitter: "https://mobile.twitter.com/search?q=%24MTVX&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/MTVX?p=MTVX&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/apt-moto-vox-pk-MTVX/trades",
      fillings:"https://www.otcmarkets.com/stock/MTVX/disclosure",  
      news:"https://www.globenewswire.com/",  
      price: "https://api.twelvedata.com/time_series?symbol=MTVX&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=MTVX&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '36',
      title: "SKYF",
      twitter: "https://mobile.twitter.com/search?q=%24SKYF&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/SKYF?p=SKYF&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/sky440-pk-SKYF/trades",
      fillings:"https://www.otcmarkets.com/stock/SKYF/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/Sky440%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=SKYF&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=SKYF&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '37',
      title: "TGRO",
      twitter: "https://mobile.twitter.com/search?q=%24TGRO&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/TGRO?p=TGRO&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/tiger-oil-and-energy-pk-TGRO/trades",
      fillings: "https://www.otcmarkets.com/stock/TGRO/disclosure",  
      news: "https://www.globenewswire.com/en/search/organization/Tiger%2520Oil%2520and%2520Energy%CE%B4%2520Inc%C2%A7?page=1",  
      price: "https://api.twelvedata.com/time_series?symbol=TGRO&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=TGRO&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '38',
      title: "PRMO",
      twitter: "https://mobile.twitter.com/search?q=%24PRMO&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/PRMO?p=PRMO&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/prom-resources-pk-PRMO/trades",
      fillings: "https://www.otcmarkets.com/stock/PRMO/disclosure",  
      news: "https://www.globenewswire.com/",  
      price: "https://api.twelvedata.com/time_series?symbol=PRMO&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=PRMO&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '39',
      title: "TBEV",
      twitter: "https://mobile.twitter.com/search?q=%24TBEV&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/TBEV?p=TBEV&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/high-performance-beverages-pk-TBEV/trades",
      fillings: "https://www.otcmarkets.com/stock/TBEV/disclosure",  
      news: "https://www.globenewswire.com/",  
      price: "https://api.twelvedata.com/time_series?symbol=TBEV&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=TBEV&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '40',
      title: "MDCN",
      twitter: "https://mobile.twitter.com/search?q=%24MDCN&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/MDCN?p=MDCN&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/medican-enterprises-pk-MDCN/trades",
      fillings: "https://www.otcmarkets.com/stock/MDCN/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Medican%252520Enterprises%252520Inc", 
      price: "https://api.twelvedata.com/time_series?symbol=MDCN&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=MDCN&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '41',
      title: "GGII",
      twitter: "https://mobile.twitter.com/search?q=%24GGII&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GGII?p=GGII&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/green-globe-pk-GGII/trades",
      fillings: "https://www.otcmarkets.com/stock/GGII/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Green%252520Globe%252520International%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=GGII&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=GGII&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '42',
      title: "EWLL",
      twitter: "https://mobile.twitter.com/search?q=%24EWLL&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/EWLL?p=EWLL&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/ewellness-healthcare-pk-EWLL/trades",
      fillings: "https://www.otcmarkets.com/stock/EWLL/disclosure",  
      news: "https://www.globenewswire.com/en/search/organization/eWellness%2520Healthcare%2520Corp?page=1",
      price: "https://api.twelvedata.com/time_series?symbol=EWLL&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=EWLL&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '43',
      title: "BCAP",
      twitter: "https://mobile.twitter.com/search?q=%24BCAP&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/BCAP?p=BCAP&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/baron-capital-enterprise-pk-BCAP/trades",
      fillings: "https://www.otcmarkets.com/stock/BCAP/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Baron%252520Capital%252520Enterprise",
      price: "https://api.twelvedata.com/time_series?symbol=BCAP&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=BCAP&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '44',
      title: "GAXY",
      twitter: "https://mobile.twitter.com/search?q=%24GAXY&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GAXY?p=GAXY&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/galaxy-next-generation-qb-GAXY/trades",
      fillings: "https://www.otcmarkets.com/stock/GAXY/disclosure",  
      news: "https://www.globenewswire.com/search/organization/Galaxy%252520Next%252520Generation",  
      price: "https://api.twelvedata.com/time_series?symbol=GAXY&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=GAXY&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '45',
      title: "GEGP",
      twitter: "https://mobile.twitter.com/search?q=%24GEGP&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GEGP?p=GEGP&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/gold-entertainment-pk-GEGP/trades",
      fillings: "https://www.otcmarkets.com/stock/GEGP/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Gold%252520Entertainment%252520Group%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=GEGP&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=GEGP&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '46',
      title: "ABVG",
      twitter: "https://mobile.twitter.com/search?q=%24ABVG&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ABVG?p=ABVG&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/affinity-beverage-ce-ABVG/trades",
      fillings: "https://www.otcmarkets.com/stock/ABVG/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Affinity%252520Beverage%252520Group%CE%B4%252520Inc%C2%A7",
      price: "https://api.twelvedata.com/time_series?symbol=ABVG&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=ABVG&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '47',
      title: "VPER",
      twitter: "https://mobile.twitter.com/search?q=%24VPER&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/VPER?p=VPER&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/viper-networks-pk-VPER/trades",
      fillings: "https://www.otcmarkets.com/stock/VPER/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Viper%252520Networks%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=VPER&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=VPER&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '48',
      title: "SIML",
      twitter: "https://mobile.twitter.com/search?q=%24SIML&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/SIML?p=SIML&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/simlatus-pk-SIML/trades",
      fillings: "https://www.otcmarkets.com/stock/SIML/disclosure",  
      news: "https://www.globenewswire.com/news-release/2021/03/04/2187078/0/en/Simlatus-Soon-to-be-BrewBilt-Brewing-Company-and-125M-Strategic-Partnership-With-BrewBilt-Manufacturing.html", 
      price: "https://api.twelvedata.com/time_series?symbol=SIML&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=SIML&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '49',
      title: "AMLH",
      twitter: "https://mobile.twitter.com/search?q=%24AMLH&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/AMLH?p=AMLH&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/american-leisure-pk-AMLH/trades",
      fillings: "https://www.otcmarkets.com/stock/AMLH/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/American%252520Leisure%252520Holdings%CE%B4%252520Inc%C2%A7",
      price: "https://api.twelvedata.com/time_series?symbol=AMLH&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=AMLH&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '50',
      title: "MRNJ",
      twitter: "https://mobile.twitter.com/search?q=%24MRNJ&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/MRNJ?p=MRNJ&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/metatron-pk-MRNJ/trades",
      fillings: "https://www.otcmarkets.com/stock/MRNJ/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Metatron%252520Inc",  
      price: "https://api.twelvedata.com/time_series?symbol=MRNJ&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=MRNJ&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '51',
      title: "CYBL",
      twitter: "https://mobile.twitter.com/search?q=%24CYBL&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/CYBL?p=CYBL&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/cyberlux-pk-CYBL/trades",
      fillings: "https://www.otcmarkets.com/stock/CYBL/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/CYBL", 
      price: "https://api.twelvedata.com/time_series?symbol=CYBL&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=CYBL&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '52',
      title: "NECA",
      twitter: "https://mobile.twitter.com/search?q=%24NECA&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/NECA?p=NECA&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/new-america-energy-pk-NECA/trades",
      fillings: "https://www.otcmarkets.com/stock/NECA/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/NECA,New%252520America%252520Energy%252520Corp%C2%A7",
      price: "https://api.twelvedata.com/time_series?symbol=NECA&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=NECA&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '53',
      title: "BSSP",
      twitter: "https://mobile.twitter.com/search?q=%24BSSP&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/BSSP?p=BSSP&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/bassline-productions-pk-BSSP/trades",
      fillings: "https://www.otcmarkets.com/stock/BSSP/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Bassline%252520Productions",  
      price: "https://api.twelvedata.com/time_series?symbol=BSSP&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=BSSP&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '54',
      title: "ETEK",
      twitter: "https://mobile.twitter.com/search?q=%24ETEK&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ETEK?p=ETEK&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/eco-tek-pk-ETEK/trades",
      fillings: "https://www.otcmarkets.com/stock/ETEK/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Eco-Tek%252520Group%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=ETEK&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=ETEK&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '55',
      title: "PLYZ",
      twitter: "https://mobile.twitter.com/search?q=%24PLYZ&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/PLYZ?p=PLYZ&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/plyzer-technologies-pk-PLYZ/trades",
      fillings: "https://www.otcmarkets.com/stock/PLYZ/disclosure",  
      news: "https://www.globenewswire.com/search",  
      price: "https://api.twelvedata.com/time_series?symbol=PLYZ&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=PLYZ&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '56',
      title: "OCLG",
      twitter: "https://mobile.twitter.com/search?q=%24OCLG&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/OCLG?p=OCLG&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/oncologix-tech-pk-OCLG/trades",
      fillings: "https://www.otcmarkets.com/stock/OCLG/disclosure",  
      news: "https://www.globenewswire.com/search",  
      price: "https://api.twelvedata.com/time_series?symbol=OCLG&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=OCLG&apikey=a5e118f7893f4e8f9428f4ef74206850", 
    },
  {
      _id: '57',
      title: "TGGI",
      twitter: "https://mobile.twitter.com/search?q=%24TGGI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/TGGI?p=TGGI&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/trans-global-pk-TGGI/trades",
      fillings: "https://www.otcmarkets.com/stock/TGGI/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Trans%252520Global%252520Group%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=TGGI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=TGGI&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '58',
      title: "GTLL",
      twitter: "https://mobile.twitter.com/search?q=%24GTLL&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GTLL?p=GTLL&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/global-technologies-pk-GTLL/trades",
      fillings: "https://www.otcmarkets.com/stock/GTLL/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Global%252520Technologies%CE%B4%252520Ltd", 
      price: "https://api.twelvedata.com/time_series?symbol=GTLL&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=GTLL&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '59',
      title: "GNCP",
      twitter: "https://mobile.twitter.com/search?q=%24GNCP&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GNCP?p=GNCP&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/gncc-capital-pk-GNCP/trades",
      fillings: "https://www.otcmarkets.com/stock/GNCP/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Global%252520Technologies%CE%B4%252520Ltd",  
      price: "https://api.twelvedata.com/time_series?symbol=GNCP&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=GNCP&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '60',
      title: "QEDN",
      twitter: "https://mobile.twitter.com/search?q=%24QEDN&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/QEDN?p=QEDN&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/qed-connect-pk-QEDN/trades",
      fillings: "https://www.otcmarkets.com/stock/QEDN/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/QED%252520Connect%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=QEDN&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=QEDN&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '61',
      title: "SHOM",
      twitter: "https://mobile.twitter.com/search?q=%24SHOM&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/SHOM?p=SHOM&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/southern-home-medical-pk-SHOM/trades",
      fillings: "https://www.otcmarkets.com/stock/SHOM/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Southern%252520Home%252520Medical%252520Equipment%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=SHOM&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=SHOM&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '62',
      title: "FCGD",
      twitter: "https://mobile.twitter.com/search?q=%24FCGD&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/FCGD?p=FCGD&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/first-colombia-gold-pk-FCGD/trades",
      fillings: "https://www.otcmarkets.com/stock/FCGD/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/First%252520Colombia%252520Gold%252520Corp%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=FCGD&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=FCGD&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '63',
      title: "HPIL",
      twitter: "https://mobile.twitter.com/search?q=%24HPIL&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/HPIL?p=HPIL&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/hpil-pk-HPIL/trades",
      fillings: "https://www.otcmarkets.com/stock/HPIL/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/HPIL%252520HOLDING",  
      price: "https://api.twelvedata.com/time_series?symbol=HPIL&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=HPIL&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '64',
      title: "TWOH",
      twitter: "https://mobile.twitter.com/search?q=%24TWOH&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/TWOH?p=TWOH&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/two-hands-pk-TWOH/trades",
      fillings: "https://www.otcmarkets.com/stock/TWOH/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Two%252520Hands%252520Corporation",  
      price: "https://api.twelvedata.com/time_series?symbol=TWOH&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=TWOH&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '65',
      title: "HBRM",
      twitter: "https://mobile.twitter.com/search?q=%24HBRM&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/HBRM?p=HBRM&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/herborium-pk-HBRM/trades",
      fillings: "https://www.otcmarkets.com/stock/HBRM/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Herborium%252520Group%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=HBRM&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=HBRM&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '66',
      title: "TMGI",
      twitter: "https://mobile.twitter.com/search?q=%24TMGI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/TMGI?p=TMGI&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/marquie-pk-TMGI/trades",
      fillings: "https://www.otcmarkets.com/stock/TMGI/disclosure",  
      news: "https://www.globenewswire.com/en/search/organization/The%2520Marquie%2520Group",  
      price: "https://api.twelvedata.com/time_series?symbol=TMGI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=TMGI&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '67',
      title: "VBHI",
      twitter: "https://mobile.twitter.com/search?q=%24VBHI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/VBHI?p=VBHI&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/verde-bio-pk-VBHI/trades",
      fillings: "https://www.otcmarkets.com/stock/VBHI/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Verde%252520Bio%252520Holdings%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=VBHI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=VBHI&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '68',
      title: "SEEK",
      twitter: "https://mobile.twitter.com/search?q=%24SEEK&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/SEEK?p=SEEK&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/thedirectory-com-pk-SEEK/trades",
      fillings: "https://www.otcmarkets.com/stock/SEEK/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Seek",  
      price: "https://api.twelvedata.com/time_series?symbol=SEEK&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=SEEK&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '69',
      title: "DRNG",
      twitter: "https://mobile.twitter.com/search?q=%24DRNG&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/DRNG?p=DRNG&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/drone-guarder-pk-DRNG/trades",
      fillings: "https://www.otcmarkets.com/stock/DRNG/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Drone%252520Guarder",  
      price: "https://api.twelvedata.com/time_series?symbol=SEEK&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=DRNG&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '70',
      title: "ATYG",
      twitter: "https://mobile.twitter.com/search?q=%24ATYG&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ATYG?p=ATYG&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/atlas-technology-pk-ATYG/trades",
      fillings: "https://www.otcmarkets.com/stock/ATYG/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/ATYG",  
      price: "https://api.twelvedata.com/time_series?symbol=ATYG&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=ATYG&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '71',
      title: "ITVI",
      twitter: "https://mobile.twitter.com/search?q=%24ITVI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ITVI?p=ITVI&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/interact-tv-pk-ITVI/trades",
      fillings: "https://www.otcmarkets.com/stock/ITVI/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Interact%252520TV",  
      price: "https://api.twelvedata.com/time_series?symbol=ITVI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=ITVI&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '72',
      title: "NNRX",
      twitter: "https://mobile.twitter.com/search?q=%24NNRX&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/NNRX?p=NNRX&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/nutranomics-pk-NNRX/trades",
      fillings: "https://www.otcmarkets.com/stock/NNRX/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/NutraNomics%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=NNRX&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=NNRX&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '73',
      title: "TXTM",
      twitter: "https://mobile.twitter.com/search?q=%24TXTM&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/TXTM?p=TXTM&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/protext-mobility-pk-TXTM/trades",
      fillings: "https://www.otcmarkets.com/stock/TXTM/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Protext%252520Mobility",  
      price: "https://api.twelvedata.com/time_series?symbol=TXTM&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=TXTM&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '74',
      title: "FONU",
      twitter: "https://mobile.twitter.com/search?q=%24FONU&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/FONU?p=FONU&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/fonu2-pk-FONU/trades",
      fillings: "https://www.otcmarkets.com/stock/FONU/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/FONU2%252520INC%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=FONU&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=FONU&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '75',
      title: "GVSI",
      twitter: "https://mobile.twitter.com/search?q=%24GVSI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GVSI?p=GVSI&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/good-vibrations-shoes-pk-GVSI/trades",
      fillings: "https://www.otcmarkets.com/stock/GVSI/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Good%252520Vibrations%252520Shoes",  
      price: "https://api.twelvedata.com/time_series?symbol=GVSI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=GVSI&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '76',
      title: "APPZ",
      twitter: "https://mobile.twitter.com/search?q=%24APPZ&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/APPZ?p=APPZ&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/monster-arts-pk-APPZ/trades",
      fillings: "https://www.otcmarkets.com/stock/APPZ/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Monster%252520Arts",  
      price: "https://api.twelvedata.com/time_series?symbol=APPZ&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=APPZ&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '77',
      title: "WRFX",
      twitter: "https://mobile.twitter.com/search?q=%24WRFX&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/WRFX?p=WRFX&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/worldflix-pk-WRFX/trades",
      fillings: "https://www.otcmarkets.com/stock/WRFX/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/WorldFlix%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=WRFX&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=WRFX&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '78',
      title: "ABWN",
      twitter: "https://mobile.twitter.com/search?q=%24ABWN&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ABWN?p=ABWN&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/airborne-wireless-network-pk-ABWN/trades",
      fillings: "https://www.otcmarkets.com/stock/ABWN/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Airborne%252520Wireless%252520Network",  
      price: "https://api.twelvedata.com/time_series?symbol=ABWN&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=ABWN&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '79',
      title: "INCT",
      twitter: "https://mobile.twitter.com/search?q=%24INCT&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/INCT?p=INCT&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/incapta-pk-INCT/trades",
      fillings: "https://www.otcmarkets.com/stock/INCT/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/InCapta%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=INCT&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=INCT&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '80',
      title: "ICTY",
      twitter: "https://mobile.twitter.com/search?q=%24ICTY&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ICTY?p=ICTY&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/eyecity-com-pk-ICTY/trades",
      fillings: "https://www.otcmarkets.com/stock/ICTY/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/EyeCity%C2%A7com%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=ICTY&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=ICTY&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '81',
      title: "KYNC",
      twitter: "https://mobile.twitter.com/search?q=%24KYNC&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/KYNC?p=KYNC&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/kyn-capital-pk-KYNC/trades",
      fillings: "https://www.otcmarkets.com/stock/KYNC/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/KYN%252520Capital%252520Group%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=KYNC&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=KYNC&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '82',
      title: "FTWS",
      twitter: "https://mobile.twitter.com/search?q=%24FTWS&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/FTWS?p=FTWS&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/flitways-technology-pk-FTWS/trades",
      fillings: "https://www.otcmarkets.com/stock/FTWS/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/FlitWays%252520Technology%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=FTWS&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=FTWS&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '83',
      title: "HVCW",
      twitter: "https://mobile.twitter.com/search?q=%24HVCW&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/HVCW?p=HVCW&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/harrison-vickers-and-wat-pk-HVCW/trades",
      fillings: "https://www.otcmarkets.com/stock/HVCW/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/hvcw",  
      price: "https://api.twelvedata.com/time_series?symbol=HVCW&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=HVCW&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '84',
      title: "CFGX",
      twitter: "https://mobile.twitter.com/search?q=%24CFGX&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/CFGX?p=CFGX&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/capital-financial-global-pk-CFGX/trades",
      fillings: "https://www.otcmarkets.com/stock/CFGX/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Capital%252520Financial%252520Global%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=CFGX&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=CFGX&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '85',
      title: "PYCT",
      twitter: "https://mobile.twitter.com/search?q=%24PYCT&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/PYCT?p=PYCT&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/paychest-pk-PYCT/trades",
      fillings: "https://www.otcmarkets.com/stock/PYCT/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Paychest",  
      price: "https://api.twelvedata.com/time_series?symbol=PYCT&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=PYCT&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '86',
      title: "CTLE",
      twitter: "https://mobile.twitter.com/search?q=%24CTLE&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/CTLE?p=CTLE&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/nano-labs-pk-CTLE/trades",
      fillings: "https://www.otcmarkets.com/stock/CTLE/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Nano%252520Labs%252520Corp%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=CTLE&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=CTLE&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '87',
      title: "RNVA",
      twitter: "https://mobile.twitter.com/search?q=%24RNVA&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/RNVA?p=RNVA&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/rennova-health-pk-RNVA/trades",
      fillings: "https://www.otcmarkets.com/stock/RNVA/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Rennova%252520Health%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=RNVA&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=RNVA&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '88',
      title: "WNBD",
      twitter: "https://mobile.twitter.com/search?q=%24WNBD&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/WNBD?p=WNBD&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/winning-brands-pk-WNBD/trades",
      fillings: "https://www.otcmarkets.com/stock/WNBD/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Winning%252520Brands%252520Corporation",  
      price: "https://api.twelvedata.com/time_series?symbol=WNBD&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=WNBD&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '89',
      title: "GTEH",
      twitter: "https://mobile.twitter.com/search?q=%24GTEH&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GTEH?p=GTEH&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/gentech-pk-GTEH/trades",
      fillings: "https://www.otcmarkets.com/stock/GTEH/disclosure",  
      news: "https://www.globenewswire.com/en/search/organization/GenTech%2520Holdings%CE%B4%2520Inc%C2%A7?page=1",  
      price: "https://api.twelvedata.com/time_series?symbol=GTEH&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=GTEH&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '90',
      title: "APYP",
      twitter: "https://mobile.twitter.com/search?q=%24APYP&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/APYP?p=APYP&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/appyea-pk-APYP/trades",
      fillings: "https://www.otcmarkets.com/stock/APYP/disclosure",  
      news: "https://www.globenewswire.com/en/search/organization/AppYea%CE%B4%2520Inc%C2%A7?page=1",  
      price: "https://api.twelvedata.com/time_series?symbol=APYP&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=APYP&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '91',
      title: "PHIL",
      twitter: "https://mobile.twitter.com/search?q=%24PHIL&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/PHIL?p=PHIL&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/phi-pk-PHIL/trades",
      fillings: "https://www.otcmarkets.com/stock/PHIL/disclosure",  
      news: "https://www.globenewswire.com/en/search/organization/PHI%2520Group%CE%B4%2520Inc%C2%A7?page=1",  
      price: "https://api.twelvedata.com/time_series?symbol=PHIL&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=PHIL&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '92',
      title: "SANP",
      twitter: "https://mobile.twitter.com/search?q=%24SANP&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/SANP?p=SANP&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/santo-mining-pk-SANP/trades",
      fillings: "https://www.otcmarkets.com/stock/SANP/disclosure",  
      news: "https://www.globenewswire.com/en/search/organization/Santo%2520Mining%2520Corp?page=1",  
      price: "https://api.twelvedata.com/time_series?symbol=SANP&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=SANP&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '93',
      title: "BRYYF",
      twitter: "https://mobile.twitter.com/search?q=%24BRYYF&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/BRYYF?p=BRYYF&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/amani-gold-pk-BRYYF/trades",
      fillings: "https://www.otcmarkets.com/stock/BRYYF/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/BRYYF",  
      price: "https://api.twelvedata.com/time_series?symbol=BRYYF&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=BRYYF&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '94',
      title: "SSFT",
      twitter: "https://mobile.twitter.com/search?q=%24SSFT&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/SSFT?p=SSFT&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/sonasoft-qb-SSFT/trades",
      fillings: "https://www.otcmarkets.com/stock/SSFT/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Sonasoft%252520Corp%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=SSFT&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=SSFT&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '95',
      title: "AAPT",
      twitter: "https://mobile.twitter.com/search?q=%24AAPT&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/AAPT?p=AAPT&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/all-american-pet-pk-AAPT/trades",
      fillings: "https://www.otcmarkets.com/stock/AAPT/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/AAPT",  
      price: "https://api.twelvedata.com/time_series?symbol=AAPT&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=AAPT&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '96',
      title: "BANT",
      twitter: "https://mobile.twitter.com/search?q=%24BANT&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/BANT?p=BANT&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/bantec-pk-BANT/trades",
      fillings: "https://www.otcmarkets.com/stock/BANT/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/BANT",  
      price: "https://api.twelvedata.com/time_series?symbol=BANT&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=BANT&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '97',
      title: "RNWR",
      twitter: "https://mobile.twitter.com/search?q=%24RNWR&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/RNWR?p=RNWR&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/808-renewable-energy-pk-RNWR/trades",
      fillings: "https://www.otcmarkets.com/stock/RNWR/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/808%252520Renewable%252520Energy%252520Corporation",  
      price: "https://api.twelvedata.com/time_series?symbol=RNWR&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=RNWR&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '98',
      title: "NIHK",
      twitter: "https://mobile.twitter.com/search?q=%24NIHK&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/NIHK?p=NIHK&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/video-river-networks-pk-NIHK/trades",
      fillings: "https://www.otcmarkets.com/stock/NIHK/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Video%252520River%252520Networks%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=NIHK&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=NIHK&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '99',
      title: "GMPW",
      twitter: "https://mobile.twitter.com/search?q=%24GMPW&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GMPW?p=GMPW&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/give-me-power-pk-GMPW/trades",
      fillings: "https://www.otcmarkets.com/stock/GMPW/disclosure",  
      news: "https://www.globenewswire.com/en/search/organization/GiveMePower%2520Corporation?page=1",  
      price: "https://api.twelvedata.com/time_series?symbol=GMPW&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=GMPW&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '100',
      title: "RGBP",
      twitter: "https://mobile.twitter.com/search?q=%24RGBP&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/RGBP?p=RGBP&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/regen-biopharma-pk-RGBP/trades",
      fillings: "https://www.otcmarkets.com/stock/RGBP/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Regen%252520Biopharma",  
      price: "https://api.twelvedata.com/time_series?symbol=RGBP&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=RGBP&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '101',
      title: "AFOM",
      twitter: "https://mobile.twitter.com/search?q=%24AFOM&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/AFOM?p=AFOM&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/all-for-one-media-pk-AFOM/trades",
      fillings: "https://www.otcmarkets.com/stock/AFOM/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/All%252520For%252520One%252520Media",  
      price: "https://api.twelvedata.com/time_series?symbol=AFOM&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=AFOM&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '102',
      title: "RTON",
      twitter: "https://mobile.twitter.com/search?q=%24RTON&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/RTON?p=RTON&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/right-on-brands-pk-RTON/trades",
      fillings: "https://www.otcmarkets.com/stock/RTON/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Right%252520On%252520Brands%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=RTON&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=RTON&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '103',
      title: "RETC",
      twitter: "https://mobile.twitter.com/search?q=%24RETC&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/RETC?p=RETC&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/12-retech-pk-RETC/trades",
      fillings: "https://www.otcmarkets.com/stock/RETC/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/12%252520Retech%252520Corporation",  
      price: "https://api.twelvedata.com/time_series?symbol=RETC&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=RETC&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '104',
      title: "DRNK",
      twitter: "https://mobile.twitter.com/search?q=%24DRNK&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/DRNK?p=DRNK&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/noho-pk-DRNK/trades",
      fillings: "https://www.otcmarkets.com/stock/DRNK/disclosure",  
      news: "https://www.globenewswire.com/en/search/organization/NOHO%CE%B4%2520Inc%C2%A7?page=1",  
      price: "https://api.twelvedata.com/time_series?symbol=DRNK&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=DRNK&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '105',
      title: "RIII",
      twitter: "https://mobile.twitter.com/search?q=%24RIII&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/RIII?p=RIII&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/renavotio-qb-RIII/trades",
      fillings: "https://www.otcmarkets.com/stock/RIII/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Renavotio%252520Inc%C2%A7%252520and%252520Emerging%252520Markets%252520Consulting%CE%B4%252520LLC%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=RIII&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=RIII&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '106',
      title: "GMEV",
      twitter: "https://mobile.twitter.com/search?q=%24GMEV&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GMEV?p=GMEV&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/gme-innotainment-pk-GMEV/trades",
      fillings: "https://www.otcmarkets.com/stock/GMEV/disclosure",  
      news: "https://finance.yahoo.com/finance/news/foundation-farms-corp-third-growth-114500505.html",  
      price: "https://api.twelvedata.com/time_series?symbol=GMEV&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=GMEV&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '107',
      title: "WDLF",
      twitter: "https://mobile.twitter.com/search?q=%24WDLF&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/WDLF?p=WDLF&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/social-life-network-pk-WDLF/trades",
      fillings: "https://www.otcmarkets.com/stock/WDLF/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Social%252520Life%252520Network%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=WDLF&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=WDLF&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '108',
      title: "WTII",
      twitter: "https://mobile.twitter.com/search?q=%24WTII&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/WTII?p=WTII&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/water-technologies-pk-WTII/trades",
      fillings: "https://www.otcmarkets.com/stock/WTII/disclosure",  
      news: "https://www.globenewswire.com/en/search/organization/Water%2520Technologies%2520International%CE%B4%2520Inc%C2%A7?page=1",  
      price: "https://api.twelvedata.com/time_series?symbol=WTII&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=WTII&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '109',
      title: "RDAR",
      twitter: "https://mobile.twitter.com/search?q=%24RDAR&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/RDAR?p=RDAR&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/raadr-pk-RDAR/trades",
      fillings: "https://www.otcmarkets.com/stock/RDAR/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/RAADR%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=RDAR&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=RDAR&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '110',
      title: "AHFD",
      twitter: "https://mobile.twitter.com/search?q=%24AHFD&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/AHFD?p=AHFD&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/active-health-foods-pk-AHFD/trades",
      fillings: "https://www.otcmarkets.com/stock/AHFD/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Active%252520Health%252520Foods",  
      price: "https://api.twelvedata.com/time_series?symbol=AHFD&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=AHFD&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '111',
      title: "NBRI",
      twitter: "https://mobile.twitter.com/search?q=%24NBRI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/NBRI?p=NBRI&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/north-bay-resources-pk-NBRI/trades",
      fillings: "https://www.otcmarkets.com/stock/NBRI/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/North%252520Bay%252520Resources%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=NBRI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=NBRI&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '112',
      title: "ILUS",
      twitter: "https://mobile.twitter.com/search?q=%24ILUS&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ILUS?p=ILUS&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/ilustrato-pictures-pk-ILUS/trades",
      fillings: "https://www.otcmarkets.com/stock/ILUS/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Ilustrato%252520Pictures%252520International%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=ILUS&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=ILUS&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '113',
      title: "FERN",
      twitter: "https://mobile.twitter.com/search?q=%24FERN&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/FERN?p=FERN&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/fernhill-pk-FERN/trades",
      fillings: "https://www.otcmarkets.com/stock/FERN/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Fernhill%252520Corporation",  
      price: "https://api.twelvedata.com/time_series?symbol=FERN&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=FERN&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '114',
      title: "ATIG",
      twitter: "https://mobile.twitter.com/search?q=%24ATIG&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ATIG?p=ATIG&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/atlantis-internet-pk-ATIG/trades",
      fillings: "https://www.otcmarkets.com/stock/ATIG/disclosure",  
      news: "https://www.globenewswire.com/en/search/organization/Atlantis%2520Internet%2520Group%2520Corporation?page=1",  
      price: "https://api.twelvedata.com/time_series?symbol=ATIG&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=ATIG&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '115',
      title: "SDEC",
      twitter: "https://mobile.twitter.com/search?q=%24SDEC&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/SDEC?p=SDEC&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/smart-decision-pk-SDEC/trades",
      fillings: "https://www.otcmarkets.com/stock/SDEC/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Smart%252520Decision%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=SDEC&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=SDEC&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '116',
      title: "APTY",
      twitter: "https://mobile.twitter.com/search?q=%24APTY&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/APTY?p=APTY&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/apt-systems-pk-APTY/trades",
      fillings: "https://www.otcmarkets.com/stock/APTY/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/APT%252520Systems%CE%B4%252520Inc",  
      price: "https://api.twelvedata.com/time_series?symbol=APTY&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=APTY&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '117',
      title: "ENTI",
      twitter: "https://mobile.twitter.com/search?q=%24ENTI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ENTI?p=ENTI&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/encounter-technologies-pk-ENTI/trades",
      fillings: "https://www.otcmarkets.com/stock/ENTI/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Encounter%252520Technologies%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=ENTI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=ENTI&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '118',
      title: "WSFT",
      twitter: "https://mobile.twitter.com/search?q=%24WSFT&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/WSFT?p=WSFT&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/wikisoft-pk-WSFT/trades",
      fillings: "https://www.otcmarkets.com/stock/WSFT/disclosure",  
      news: "https://www.globenewswire.com/en/search/organization/WikiSoft%2520Corp%C2%A7?page=1",  
      price: "https://api.twelvedata.com/time_series?symbol=WSFT&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=WSFT&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '119',
      title: "DSCR",
      twitter: "https://mobile.twitter.com/search?q=%24DSCR&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/DSCR?p=DSCR&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/discovery-minerals-pk-DSCR/trades",
      fillings: "https://www.otcmarkets.com/stock/DSCR/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Discovery%252520Minerals%252520Ltd",  
      price: "https://api.twelvedata.com/time_series?symbol=DSCR&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=DSCR&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '120',
      title: "FWDG",
      twitter: "https://mobile.twitter.com/search?q=%24FWDG&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/FWDG?p=FWDG&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/futureworld-pk-FWDG/trades",
      fillings: "https://www.otcmarkets.com/stock/FWDG/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/FutureWorld%252520Corp",  
      price: "https://api.twelvedata.com/time_series?symbol=FWDG&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=FWDG&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '121',
      title: "PVSP",
      twitter: "https://mobile.twitter.com/search?q=%24PVSP&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/PVSP?p=PVSP&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/pervasip-pk-PVSP/trades",
      fillings: "https://www.otcmarkets.com/stock/PVSP/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Pervasip%252520Corp%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=PVSP&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=PVSP&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '122',
      title: "SUTI",
      twitter: "https://mobile.twitter.com/search?q=%24SUTI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/SUTI?p=SUTI&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/sutimco-pk-SUTI/trades",
      fillings: "https://www.otcmarkets.com/stock/SUTI/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/SUTI",  
      price: "https://api.twelvedata.com/time_series?symbol=SUTI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=SUTI&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '123',
      title: "ASTI",
      twitter: "https://mobile.twitter.com/search?q=%24ASTI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ASTI?p=ASTI&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/ascent-solar-technologies-pk-ASTI/trades",
      fillings: "https://www.otcmarkets.com/stock/ASTI/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/ASTI",  
      price: "https://api.twelvedata.com/time_series?symbol=ASTI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=ASTI&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '124',
      title: "PDGO",
      twitter: "https://mobile.twitter.com/search?q=%24PDGO&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/PDGO?p=PDGO&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/paradigm-oil-and-gas-pk-PDGO/trades",
      fillings: "https://www.otcmarkets.com/stock/PDGO/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Paradigm%252520Oil%252520and%252520Gas",  
      price: "https://api.twelvedata.com/time_series?symbol=PDGO&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=PDGO&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '125',
      title: "HDII",
      twitter: "https://mobile.twitter.com/search?q=%24HDii&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/HDII?p=HDII&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/hypertension-diagnositc-pk-HDII/trades",
      fillings: "https://www.otcmarkets.com/stock/HDII/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/HDII",  
      price: "https://api.twelvedata.com/time_series?symbol=HDII&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=HDII&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '126',
      title: "MNVN",
      twitter: "https://mobile.twitter.com/search?q=%24MNVN&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/MNVN?p=MNVN&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/mondial-ventures-pk-MNVN/trades",
      fillings: "https://www.otcmarkets.com/stock/MNVN/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/mondial%252520ventures",  
      price: "https://api.twelvedata.com/time_series?symbol=MNVN&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=MNVN&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '127',
      title: "ASKE",
      twitter: "https://mobile.twitter.com/search?q=%24ASKE&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ASKE?p=ASKE&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/alaska-pacific-energy-pk-ASKE/trades",
      fillings: "https://www.otcmarkets.com/stock/ASKE/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/ASKE",  
      price: "https://api.twelvedata.com/time_series?symbol=ASKE&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=ASKE&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '128',
      title: "WWIO",
      twitter: "https://mobile.twitter.com/search?q=%24WWIO&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/WWIO?p=WWIO&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/wowio-pk-WWIO/trades",
      fillings: "https://www.otcmarkets.com/stock/WWIO/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Wowio%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=WWIO&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=WWIO&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '129',
      title: "RYCEY",
      twitter: "https://mobile.twitter.com/search?q=%24RYCEY&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/RYCEY?p=RYCEY&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/rolls-royce-pk-RYCEY/trades",
      fillings: "https://www.otcmarkets.com/stock/RYCEY/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Rolls-Royce%252520PLC",  
      price: "https://api.twelvedata.com/time_series?symbol=RYCEY&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=RYCEY&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '130',
      title: "ICOA",
      twitter: "https://mobile.twitter.com/search?q=%24ICOA&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ICOA?p=ICOA&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/icoa-pk-ICOA/trades",
      fillings: "https://www.otcmarkets.com/stock/ICOA/disclosure",  
      news: "https://www.globenewswire.com/search/organization/ICOA%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=ICOA&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=ICOA&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '131',
      title: "JAMN",
      twitter: "https://mobile.twitter.com/search?q=%24JAMN&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/JAMN?p=JAMN&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/jammin-java-pk-JAMN/trades",
      fillings: "https://www.otcmarkets.com/stock/JAMN/disclosure",  
      news: "https://www.globenewswire.com/search/organization/Jammin%252520Java%252520Corp%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=JAMN&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=JAMN&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '132',
      title: "PBYA",
      twitter: "https://mobile.twitter.com/search?q=%24PBYA&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/PBYA?p=PBYA&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/probility-media-pk-PBYA/trades",
      fillings: "https://www.otcmarkets.com/stock/PBYA/disclosure",  
      news: "https://www.globenewswire.com/search/organization/ProBility%252520Media%252520Corp%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=PBYA&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=PBYA&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '133',
      title: "FTXP",
      twitter: "https://mobile.twitter.com/search?q=%24FTXP&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/FTXP?p=FTXP&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/foothills-exploration-pk-FTXP/trades",
      fillings: "https://www.otcmarkets.com/stock/FTXP/disclosure",  
      news: "https://www.globenewswire.com/search/organization/Foothills%252520Exploration%CE%B4%252520Inc",  
      price: "https://api.twelvedata.com/time_series?symbol=FTXP&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=FTXP&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '134',
      title: "GRLT",
      twitter: "https://mobile.twitter.com/search?q=%24GRLT&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GRLT?p=GRLT&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/grillit-pk-GRLT/trades",
      fillings: "https://www.otcmarkets.com/stock/GRLT/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/GRILLiT%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=GRLT&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=GRLT&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    }
  ],
};
export default data;


