const data = {
  stocks: [
    {
      _id: '1',
      title: "FTEG",
      twitter: "https://mobile.twitter.com/search?q=%24FTEG&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/FTEG?p=FTEG&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/for-the-earth-pk-FTEG/trades",
      fillings:"https://www.otcmarkets.com/stock/FTEG/disclosure",  
      news:"https://www.globenewswire.com/search/organization/For%252520The%252520Earth%252520Corp%C2%A7",
      price: "https://api.twelvedata.com/time_series?symbol=FTEG&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=FTEG&apikey=a5e118f7893f4e8f9428f4ef74206850",    
    },
    {
      _id: '2',
      title: "BDGR",
      twitter: "https://mobile.twitter.com/search?q=%24BDGR&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/BDGR?p=BDGR&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/black-dragon-resource-co-pk-BDGR/trades",
      fillings:"https://www.otcmarkets.com/stock/BDGR/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Black%252520Dragon%252520Resource%252520Companies%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=BDGR&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=BDGR&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
    {
      _id: '3',
      title: "AITX",
      twitter: "https://mobile.twitter.com/search?q=%24AITX&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/AITX?p=AITX&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/artificial-intelligence-pk-AITX/trades",
      fillings:"https://www.otcmarkets.com/stock/AITX/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Artificial%252520Intelligence%252520Technology%252520Solutions", 
      price: "https://api.twelvedata.com/time_series?symbol=AITX&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=AITX&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
    {
      _id: '4',
      title: "MLHC",
      twitter: "https://mobile.twitter.com/search?q=%24MLHC&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/MLHC?p=MLHC&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/m-line-pk-MLHC/trades",
      fillings:"https://www.otcmarkets.com/stock/MLHC/disclosure",  
      news:"https://www.globenewswire.com/search/organization/M%252520Line%252520Holdings%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=MLHC&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=MLHC&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
    {
      _id: '5',
      title: "UBQU",
      twitter: "https://mobile.twitter.com/search?q=%24UBQU&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/UBQU?p=UBQU&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/ubiquitech-software-pk-UBQU/trades",
      fillings:"https://www.otcmarkets.com/stock/UBQU/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Ubiquitech%252520Software%252520LLC",  
      price: "https://api.twelvedata.com/time_series?symbol=UBQU&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=UBQU&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
    {
      _id: '6',
      title: "GARB",
      twitter: "https://mobile.twitter.com/search?q=%24GARB&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GARB?p=GARB&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/garb-oil-and-power-pk-GARB/trades",
      fillings:"https://www.otcmarkets.com/stock/GARB/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Garb%252520Oil%252520&%252520Power%252520Corporation", 
      price: "https://api.twelvedata.com/time_series?symbol=GARB&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=GARB&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
    {
      _id: '7',
      title: "ONCI",
      twitter: "https://mobile.twitter.com/search?q=%24ONCI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ONCI?p=ONCI&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/on4-communications-pk-ONCI/trades",
      fillings:"https://www.otcmarkets.com/stock/ONCI/disclosure",  
      news:"https://www.globenewswire.com/search/organization/ON4%252520Communications%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=ONCI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=ONCI&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
    {
      _id: '8',
      title: "HAON",
      twitter: "https://mobile.twitter.com/search?q=%24HAON&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/HAON?p=HAON&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/halitron-pk-HAON/trades",
      fillings:"https://www.otcmarkets.com/stock/HAON/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Halitron%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=HAON&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=HAON&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
    {
      _id: '9',
      title: "IPSI",
      twitter: "https://mobile.twitter.com/search?q=%24IPSI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/IPSI?p=IPSI&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/innovative-payment-solut-qb-IPSI/trades",
      fillings:"https://www.otcmarkets.com/stock/IPSI/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Innovative%252520Payment%252520Solutions%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=IPSI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=IPSI&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
    {
      _id: '10',
      title: "CTYX",
      twitter: "https://mobile.twitter.com/search?q=%24CTYX&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/CTYX?p=CTYX&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/connectyx-technologies-pk-CTYX/trades",
      fillings:"https://www.otcmarkets.com/stock/CTYX/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Connectyx%252520Technologies%252520Holdings%252520Group%CE%B4%252520Inc",  
      price: "https://api.twelvedata.com/time_series?symbol=CTYX&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=CTYX&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
    {
      _id: '11',
      title: "HPNN",
      twitter: "https://mobile.twitter.com/search?q=%24HPNN&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/HPNN?p=HPNN&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/hop-on-pk-HPNN/trades",
      fillings:"https://www.otcmarkets.com/stock/HPNN/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Hop-on%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=HPNN&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=HPNN&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
    {
      _id: '12',
      title: "RSHN",
      twitter: "https://mobile.twitter.com/search?q=%24RSHN&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/RSHN?p=RSHN&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/rushnet-pk-RSHN/trades",
      fillings:"https://www.otcmarkets.com/stock/RSHN/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/RushNet%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=RSHN&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=RSHN&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
    {
      _id: '13',
      title: "GDET",
      twitter: "https://mobile.twitter.com/search?q=%24GDET&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GDET?p=GDET&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/gd-entertainment-and-tec-pk-GDET/trades",
      fillings:"https://www.otcmarkets.com/stock/GDET/disclosure",  
      news:"https://www.globenewswire.com/search/organization/GD%252520Entertainment%252520&%252520Technology%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=GDET&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=GDET&apikey=a5e118f7893f4e8f9428f4ef74206850", 
    },
    {
      _id: '14',
      title: "GRLF",
      twitter: "https://mobile.twitter.com/search?q=%24GRLF&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GRLF?p=GRLF&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/green-leaf-innovations-pk-GRLF/trades",
      fillings:"https://www.otcmarkets.com/stock/GRLF/disclosure",  
      news:"https://www.globenewswire.com",  
      price: "https://api.twelvedata.com/time_series?symbol=GRLF&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=GRLF&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
    {
      _id: '15',
      title: "IGEX",
      twitter: "https://mobile.twitter.com/search?q=%24IGEX&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/IGEX?p=IGEX&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/indo-global-exchanges-pte-pk-IGEX/trades",
      fillings:"https://www.otcmarkets.com/stock/IGEX/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Indo%252520Global%252520Exchange%252520Pte%C2%A7%CE%B4%252520LTD",
      price: "https://api.twelvedata.com/time_series?symbol=IGEX&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=IGEX&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
      {
      _id: '16',
      title: "EFIR",
      twitter: "https://mobile.twitter.com/search?q=%24EFIR&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/EFIR?p=EFIR&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/egpi-firecreek-pk-EFIR/trades",
      fillings:"https://www.otcmarkets.com/stock/EFIR/disclosure",  
      news:"https://www.globenewswire.com/search/organization/EGPI%252520Firecreek%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=EFIR&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=EFIR&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
      {
      _id: '17',
      title: "BRZL",
      twitter: "https://mobile.twitter.com/search?q=%24BRZL&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/BRZL?p=BRZL&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/scepter-pk-BRZL/trades",
      fillings:"https://www.otcmarkets.com/stock/BRZL/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/BRZL",  
      price: "https://api.twelvedata.com/time_series?symbol=BRZL&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=BRZL&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '18',
      title: "MEDV",
      twitter: "https://mobile.twitter.com/search?q=%24MEDV&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/COPRF?p=COPRF&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/medivolve-pk-COPRF/trades",
      fillings:"https://www.otcmarkets.com/stock/MEDV/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/Medivolve%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=COPRF&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=COPRF&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '19',
      title: "VGID",
      twitter: "https://mobile.twitter.com/search?q=%24VGID&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/VGID?p=VGID&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/v-pk-VGID/trades",
      fillings:"https://www.otcmarkets.com/stock/VGID/disclosure",  
      news:"https://www.globenewswire.com/search/organization/V%252520Group%CE%B4%252520Inc",  
      price: "https://api.twelvedata.com/time_series?symbol=VGID&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=VGID&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
   {
      _id: '20',
      title: "SRMX",
      twitter: "https://mobile.twitter.com/search?q=%24SRMX&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/SRMX?p=SRMX&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/saddle-ranch-media-pk-SRMX/trades",
      fillings:"https://www.otcmarkets.com/stock/SRMX/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/Saddle%252520Ranch%252520Media%252520Inc",  
      price: "https://api.twelvedata.com/time_series?symbol=SRMX&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=SRMX&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '21',
      title: "PRMP",
      twitter: "https://mobile.twitter.com/search?q=%24PRPM&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/PRPM?p=PRPM&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/protek-capital-pk-PRPM/trades",
      fillings:"https://www.otcmarkets.com/stock/PRPM/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/protek%252520CAPITAL",  
      price: "https://api.twelvedata.com/time_series?symbol=PRPM&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=PRPM&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
   {
      _id: '22',
      title: "HCMC",
      twitter: "https://mobile.twitter.com/search?q=%24HCMC&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/HCMC?p=HCMC&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/healthier-choices-manage-pk-HCMC/trades",
      fillings:"https://www.otcmarkets.com/stock/HCMC/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/Healthier%252520Choices%252520Management%252520Corp",  
      price: "https://api.twelvedata.com/time_series?symbol=HCMC&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=HCMC&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '23',
      title: "QBAN",
      twitter: "https://mobile.twitter.com/search?q=%24QBAN&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/QBAN?p=QBAN&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/telco-cuba-pk-QBAN/trades",
      fillings:"https://www.otcmarkets.com/stock/QBAN/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/Telco%252520CUBA%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=QBAN&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=QBAN&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
   {
      _id: '24',
      title: "MMEX",
      twitter: "https://mobile.twitter.com/search?q=%24MMEX&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/MMEX?p=MMEX&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/mmex-resources-pk-MMEX/trades",
      fillings:"https://www.otcmarkets.com/stock/MMEX/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/MMEX%252520Resources%252520Corp%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=MMEX&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=MMEX&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '25',
      title: "MNGG",
      twitter: "https://mobile.twitter.com/search?q=%24MNGG&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/MNGG?p=MNGG&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/mining-global-pk-MNGG/trades",
      fillings:"https://www.otcmarkets.com/stock/MNGG/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Mining%252520Global%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=MNGG&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=MNGG&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
{
      _id: '26',
      title: "ICNM",
      twitter: "https://mobile.twitter.com/search?q=%24iCNM&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ICNM?p=ICNM&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/icon-media-pk-ICNM/trades",
      fillings:"https://www.otcmarkets.com/stock/ICNM/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Icon%252520Media%252520Holdings%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=ICNM&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=ICNM&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '27',
      title: "IDGC",
      twitter: "https://mobile.twitter.com/search?q=%24IDGC&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/IDGC?p=IDGC&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/id-global-pk-IDGC/trades",
      fillings:"https://www.otcmarkets.com/stock/IDGC/disclosure",  
      news:"https://www.globenewswire.com/search/organization/ID%252520Global%252520Corporation",  
      price: "https://api.twelvedata.com/time_series?symbol=IDGC&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=IDGC&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
   {
      _id: '28',
      title: "AZFL",
      twitter: "https://mobile.twitter.com/search?q=%24AZFL&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/AZFL?p=AZFL&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/amazonas-florestal-pk-AZFL/trades",
      fillings:"https://www.otcmarkets.com/stock/AZFL/disclosure",  
      news:"https://www.globenewswire.com/search/organization/Amazonas%252520Florestal%252520Ltd%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=AZFL&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=AZFL&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '29',
      title: "CZNI",
      twitter: "https://mobile.twitter.com/search?q=%24CZNI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/CZNI?p=CZNI&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/cruzani-pk-CZNI/trades",
      fillings:"https://www.otcmarkets.com/stock/CZNI/disclosure",  
      news:"https://www.globenewswire.com/search/organization/CRUZANI%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=CZNI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=CZNI&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '30',
      title: "USMJ",
      twitter: "https://mobile.twitter.com/search?q=%24USMJ&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/USMJ?p=USMJ&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/north-american-cannabis-pk-USMJ/trades",
      fillings:"https://www.otcmarkets.com/stock/USMJ/disclosure",  
      news:"https://www.globenewswire.com/search/organization/North%252520American%252520Cannabis%252520Holdings%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=USMJ&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=USMJ&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '31',
      title: "NUUU",
      twitter: "https://mobile.twitter.com/search?q=%24NUUU&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/NUUU?p=NUUU&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/rejuvel-bio-sciences-pk-NUUU/trades",
      fillings:"https://www.otcmarkets.com/stock/NUUU/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/NUUU",  
      price: "https://api.twelvedata.com/time_series?symbol=NUUU&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=NUUU&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '32',
      title: "VIZC",
      twitter: "https://mobile.twitter.com/search?q=%24VIZC&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/VIZC?p=VIZC&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/vizconnect-pk-VIZC/trades",
      fillings:"https://www.otcmarkets.com/stock/VIZC/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/VIZC",  
      price: "https://api.twelvedata.com/time_series?symbol=VIZC&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=VIZC&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '33',
      title: "PLPL",
      twitter: "https://mobile.twitter.com/search?q=%24PLPL&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/PLPL?p=PLPL&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/plandai-biotechnology-pk-PLPL/trades",
      fillings:"https://www.otcmarkets.com/stock/PLPL/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/Plandai%252520Biotechnology%CE%B4%252520Inc%C2%A7",
      price: "https://api.twelvedata.com/time_series?symbol=PLPL&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=PLPL&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '34',
      title: "NOUV",
      twitter: "https://mobile.twitter.com/search?q=%24NOUV&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/NOUV?p=NOUV&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/nouveau-life-pharmaceuti-pk-NOUV/trades",
      fillings:"https://www.otcmarkets.com/stock/NOUV/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/Nouveau%252520Life%252520Pharmaceuticals%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=NOUV&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=NOUV&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '35',
      title: "MTVX",
      twitter: "https://mobile.twitter.com/search?q=%24MTVX&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/MTVX?p=MTVX&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/apt-moto-vox-pk-MTVX/trades",
      fillings:"https://www.otcmarkets.com/stock/MTVX/disclosure",  
      news:"https://www.globenewswire.com/",  
      price: "https://api.twelvedata.com/time_series?symbol=MTVX&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=MTVX&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '36',
      title: "SKYF",
      twitter: "https://mobile.twitter.com/search?q=%24SKYF&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/SKYF?p=SKYF&.tsrc=fin-srch",
      leveltwo:"https://ih.advfn.com/stock-market/USOTC/sky440-pk-SKYF/trades",
      fillings:"https://www.otcmarkets.com/stock/SKYF/disclosure",  
      news:"https://www.globenewswire.com/search/keyword/Sky440%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=SKYF&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=SKYF&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '37',
      title: "TGRO",
      twitter: "https://mobile.twitter.com/search?q=%24TGRO&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/TGRO?p=TGRO&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/tiger-oil-and-energy-pk-TGRO/trades",
      fillings: "https://www.otcmarkets.com/stock/TGRO/disclosure",  
      news: "https://www.globenewswire.com/en/search/organization/Tiger%2520Oil%2520and%2520Energy%CE%B4%2520Inc%C2%A7?page=1",  
      price: "https://api.twelvedata.com/time_series?symbol=TGRO&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=TGRO&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '38',
      title: "PRMO",
      twitter: "https://mobile.twitter.com/search?q=%24PRMO&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/PRMO?p=PRMO&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/prom-resources-pk-PRMO/trades",
      fillings: "https://www.otcmarkets.com/stock/PRMO/disclosure",  
      news: "https://www.globenewswire.com/",  
      price: "https://api.twelvedata.com/time_series?symbol=PRMO&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=PRMO&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '39',
      title: "TBEV",
      twitter: "https://mobile.twitter.com/search?q=%24TBEV&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/TBEV?p=TBEV&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/high-performance-beverages-pk-TBEV/trades",
      fillings: "https://www.otcmarkets.com/stock/TBEV/disclosure",  
      news: "https://www.globenewswire.com/",  
      price: "https://api.twelvedata.com/time_series?symbol=TBEV&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=TBEV&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '40',
      title: "MDCN",
      twitter: "https://mobile.twitter.com/search?q=%24MDCN&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/MDCN?p=MDCN&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/medican-enterprises-pk-MDCN/trades",
      fillings: "https://www.otcmarkets.com/stock/MDCN/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Medican%252520Enterprises%252520Inc", 
      price: "https://api.twelvedata.com/time_series?symbol=MDCN&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=MDCN&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '41',
      title: "GGII",
      twitter: "https://mobile.twitter.com/search?q=%24GGII&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GGII?p=GGII&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/green-globe-pk-GGII/trades",
      fillings: "https://www.otcmarkets.com/stock/GGII/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Green%252520Globe%252520International%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=GGII&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=GGII&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '42',
      title: "EWLL",
      twitter: "https://mobile.twitter.com/search?q=%24EWLL&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/EWLL?p=EWLL&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/ewellness-healthcare-pk-EWLL/trades",
      fillings: "https://www.otcmarkets.com/stock/EWLL/disclosure",  
      news: "https://www.globenewswire.com/en/search/organization/eWellness%2520Healthcare%2520Corp?page=1",
      price: "https://api.twelvedata.com/time_series?symbol=EWLL&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=EWLL&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '43',
      title: "BCAP",
      twitter: "https://mobile.twitter.com/search?q=%24BCAP&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/BCAP?p=BCAP&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/baron-capital-enterprise-pk-BCAP/trades",
      fillings: "https://www.otcmarkets.com/stock/BCAP/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Baron%252520Capital%252520Enterprise",
      price: "https://api.twelvedata.com/time_series?symbol=BCAP&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=BCAP&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '44',
      title: "IHSI",
      twitter: "https://mobile.twitter.com/search?q=%24IHSI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/IHSI?p=IHSI&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/intelligent-highway-solu-pk-IHSI/trades",
      fillings: "https://www.otcmarkets.com/stock/IHSI/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Intelligent%252520Highway%252520Solutions%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=IHSI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=IHSI&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '45',
      title: "GEGP",
      twitter: "https://mobile.twitter.com/search?q=%24GEGP&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GEGP?p=GEGP&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/gold-entertainment-pk-GEGP/trades",
      fillings: "https://www.otcmarkets.com/stock/GEGP/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Gold%252520Entertainment%252520Group%CE%B4%252520Inc%C2%A7", 
      price: "https://api.twelvedata.com/time_series?symbol=GEGP&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=GEGP&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '46',
      title: "ABVG",
      twitter: "https://mobile.twitter.com/search?q=%24ABVG&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ABVG?p=ABVG&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/affinity-beverage-ce-ABVG/trades",
      fillings: "https://www.otcmarkets.com/stock/ABVG/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Affinity%252520Beverage%252520Group%CE%B4%252520Inc%C2%A7",
      price: "https://api.twelvedata.com/time_series?symbol=ABVG&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=ABVG&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '47',
      title: "VPER",
      twitter: "https://mobile.twitter.com/search?q=%24VPER&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/VPER?p=VPER&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/viper-networks-pk-VPER/trades",
      fillings: "https://www.otcmarkets.com/stock/VPER/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Viper%252520Networks%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=VPER&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=VPER&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '48',
      title: "SIML",
      twitter: "https://mobile.twitter.com/search?q=%24SIML&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/SIML?p=SIML&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/simlatus-pk-SIML/trades",
      fillings: "https://www.otcmarkets.com/stock/SIML/disclosure",  
      news: "https://www.globenewswire.com/news-release/2021/03/04/2187078/0/en/Simlatus-Soon-to-be-BrewBilt-Brewing-Company-and-125M-Strategic-Partnership-With-BrewBilt-Manufacturing.html", 
      price: "https://api.twelvedata.com/time_series?symbol=SIML&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=SIML&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '49',
      title: "AMLH",
      twitter: "https://mobile.twitter.com/search?q=%24AMLH&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/AMLH?p=AMLH&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/american-leisure-pk-AMLH/trades",
      fillings: "https://www.otcmarkets.com/stock/AMLH/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/American%252520Leisure%252520Holdings%CE%B4%252520Inc%C2%A7",
      price: "https://api.twelvedata.com/time_series?symbol=AMLH&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=AMLH&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '50',
      title: "MRNJ",
      twitter: "https://mobile.twitter.com/search?q=%24MRNJ&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/MRNJ?p=MRNJ&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/metatron-pk-MRNJ/trades",
      fillings: "https://www.otcmarkets.com/stock/MRNJ/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Metatron%252520Inc",  
      price: "https://api.twelvedata.com/time_series?symbol=MRNJ&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=MRNJ&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '51',
      title: "UVSE",
      twitter: "https://mobile.twitter.com/search?q=%24UVSE&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/UVSE?p=UVSE&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/universal-energy-pk-UVSE/trades",
      fillings: "https://www.otcmarkets.com/stock/UVSE/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Universal%252520Energy", 
      price: "https://api.twelvedata.com/time_series?symbol=UVSE&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=UVSE&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '52',
      title: "IRNC",
      twitter: "https://mobile.twitter.com/search?q=%24IRNC&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/IRNC?p=IRNC&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/ironclad-encryption-pk-IRNC/trades",
      fillings: "https://www.otcmarkets.com/stock/IRNC/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Ironclad%252520Encryption",
      price: "https://api.twelvedata.com/time_series?symbol=iRNC&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=irnc&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '53',
      title: "BSSP",
      twitter: "https://mobile.twitter.com/search?q=%24BSSP&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/BSSP?p=BSSP&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/bassline-productions-pk-BSSP/trades",
      fillings: "https://www.otcmarkets.com/stock/BSPP/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Bassline%252520Productions",  
      price: "https://api.twelvedata.com/time_series?symbol=BSSP&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=BSSP&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '54',
      title: "ETEK",
      twitter: "https://mobile.twitter.com/search?q=%24ETEK&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/ETEK?p=ETEK&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/eco-tek-pk-ETEK/trades",
      fillings: "https://www.otcmarkets.com/stock/ETEK/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Eco-Tek%252520Group%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=ETEK&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=ETEK&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '55',
      title: "PLYZ",
      twitter: "https://mobile.twitter.com/search?q=%24PLYZ&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/PLYZ?p=PLYZ&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/plyzer-technologies-pk-PLYZ/trades",
      fillings: "https://www.otcmarkets.com/stock/PLYZ/disclosure",  
      news: "https://www.globenewswire.com/search",  
      price: "https://api.twelvedata.com/time_series?symbol=PLYZ&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=PLYZ&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '56',
      title: "OCLG",
      twitter: "https://mobile.twitter.com/search?q=%24OCLG&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/OCLG?p=OCLG&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/oncologix-tech-pk-OCLG/trades",
      fillings: "https://www.otcmarkets.com/stock/OCLG/disclosure",  
      news: "https://www.globenewswire.com/search",  
      price: "https://api.twelvedata.com/time_series?symbol=OCLG&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=OCLG&apikey=a5e118f7893f4e8f9428f4ef74206850", 
    },
  {
      _id: '57',
      title: "TGGI",
      twitter: "https://mobile.twitter.com/search?q=%24TGGI&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/TGGI?p=TGGI&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/trans-global-pk-TGGI/trades",
      fillings: "https://www.otcmarkets.com/stock/TGGI/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Trans%252520Global%252520Group%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=TGGI&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=TGGI&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '58',
      title: "GTLL",
      twitter: "https://mobile.twitter.com/search?q=%24GTLL&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GTLL?p=GTLL&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/global-technologies-pk-GTLL/trades",
      fillings: "https://www.otcmarkets.com/stock/GTLL/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Global%252520Technologies%CE%B4%252520Ltd", 
      price: "https://api.twelvedata.com/time_series?symbol=GTLL&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850",
      target: "https://api.twelvedata.com/price?symbol=GTLL&apikey=a5e118f7893f4e8f9428f4ef74206850",   
    },
  {
      _id: '59',
      title: "GNCP",
      twitter: "https://mobile.twitter.com/search?q=%24GNCP&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/GNCP?p=GNCP&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/global-technologies-pk-GTLL/trades",
      fillings: "https://www.otcmarkets.com/stock/GNCP/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Global%252520Technologies%CE%B4%252520Ltd",  
      price: "https://api.twelvedata.com/time_series?symbol=GNCP&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=GNCP&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '60',
      title: "QEDN",
      twitter: "https://mobile.twitter.com/search?q=%24QEDN&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/QEDN?p=QEDN&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/qed-connect-pk-QEDN/trades",
      fillings: "https://www.otcmarkets.com/stock/QEDN/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/QED%252520Connect%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=QEDN&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=QEDN&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '61',
      title: "SHOM",
      twitter: "https://mobile.twitter.com/search?q=%24SHOM&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/SHOM?p=SHOM&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/southern-home-medical-pk-SHOM/trades",
      fillings: "https://www.otcmarkets.com/stock/SHOM/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Southern%252520Home%252520Medical%252520Equipment%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=SHOM&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=SHOM&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '62',
      title: "FCGD",
      twitter: "https://mobile.twitter.com/search?q=%24FCGD&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/FCGD?p=FCGD&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/first-colombia-gold-pk-FCGD/trades",
      fillings: "https://www.otcmarkets.com/stock/FCGD/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/First%252520Colombia%252520Gold%252520Corp%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=FCGD&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=FCGD&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '63',
      title: "HPIL",
      twitter: "https://mobile.twitter.com/search?q=%24HPIL&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/HPIL?p=HPIL&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/hpil-pk-HPIL/trades",
      fillings: "https://www.otcmarkets.com/stock/HPIL/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/HPIL%252520HOLDING",  
      price: "https://api.twelvedata.com/time_series?symbol=HPIL&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=HPIL&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '64',
      title: "TWOH",
      twitter: "https://mobile.twitter.com/search?q=%24TWOH&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/TWOH?p=TWOH&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/two-hands-pk-TWOH/trades",
      fillings: "https://www.otcmarkets.com/stock/TWOH/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Two%252520Hands%252520Corporation",  
      price: "https://api.twelvedata.com/time_series?symbol=TWOH&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=TWOH&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  {
      _id: '65',
      title: "HBRM",
      twitter: "https://mobile.twitter.com/search?q=%24HBRM&src=typed_query&f=live",
      chart: "https://finance.yahoo.com/quote/HBRM?p=HBRM&.tsrc=fin-srch",
      leveltwo: "https://ih.advfn.com/stock-market/USOTC/herborium-pk-HBRM/trades",
      fillings: "https://www.otcmarkets.com/stock/HBRM/disclosure",  
      news: "https://www.globenewswire.com/search/keyword/Herborium%252520Group%CE%B4%252520Inc%C2%A7",  
      price: "https://api.twelvedata.com/time_series?symbol=HBRM&interval=1min&apikey=a5e118f7893f4e8f9428f4ef74206850", 
      target: "https://api.twelvedata.com/price?symbol=HBRM&apikey=a5e118f7893f4e8f9428f4ef74206850",  
    },
  ],
};
export default data;


